/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.shop;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class CustomerInfo extends javax.swing.JFrame {

    /**
     * Creates new form CustomerInfo
     */
    public CustomerInfo() {
        initComponents();
        table_update();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnInventoryToHome = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtC_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtC_shopName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtC_address = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtC_mobile = new javax.swing.JTextField();
        btn_c_submit = new javax.swing.JButton();
        btnRemoveProduct = new javax.swing.JButton();
        btnRemoveProduct1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        btnInventoryToHome.setBackground(new java.awt.Color(255, 255, 204));
        btnInventoryToHome.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnInventoryToHome.setText("Go to home page>");
        btnInventoryToHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventoryToHomeActionPerformed(evt);
            }
        });

        jLabel1.setText("Name :");

        jLabel2.setText("Shop Name :");

        jLabel3.setText("address :");

        jLabel4.setText("Mobile :");

        btn_c_submit.setBackground(new java.awt.Color(255, 51, 51));
        btn_c_submit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_c_submit.setText("Submit");
        btn_c_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_c_submitActionPerformed(evt);
            }
        });

        btnRemoveProduct.setBackground(new java.awt.Color(255, 102, 102));
        btnRemoveProduct.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnRemoveProduct.setText("Delete");
        btnRemoveProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveProductActionPerformed(evt);
            }
        });

        btnRemoveProduct1.setBackground(new java.awt.Color(255, 102, 102));
        btnRemoveProduct1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnRemoveProduct1.setText("Edit ");
        btnRemoveProduct1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveProduct1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(btnInventoryToHome, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtC_shopName, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtC_name, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtC_address, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtC_mobile, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(btnRemoveProduct1)
                        .addGap(58, 58, 58)
                        .addComponent(btn_c_submit)
                        .addGap(59, 59, 59)
                        .addComponent(btnRemoveProduct)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnInventoryToHome)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtC_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtC_shopName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtC_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtC_mobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRemoveProduct1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_c_submit)
                            .addComponent(btnRemoveProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(133, 133, 133))))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Name", "Shop Name", "Shop Address", "Mobile"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(155, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
        Connection con1;
        PreparedStatement insert;
        private void table_update(){
                int c;

                    try {
                        Class.forName("com.mysql.jdbc.Driver");
                        con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/shop_manage","root","Majumder@reshad");
                        insert = con1.prepareStatement("select * from customer ");
                        ResultSet rs = insert.executeQuery();
                        ResultSetMetaData rssm = rs.getMetaData();

                        c=rssm.getColumnCount();

                        DefaultTableModel Df = (DefaultTableModel)jTable1.getModel();

                        Df.setRowCount(0);
                        while(rs.next()){

                        Vector v2=new Vector();

                        for(int a = 1;a<=c;a++){
                            v2.add(rs.getString("id"));
                            v2.add(rs.getString("name"));
                            v2.add(rs.getString("shop_name"));
                            v2.add(rs.getString("address"));
                            v2.add(rs.getString("mobile"));

                        }

                        Df.addRow(v2);


                    }



                        //JOptionPane.showMessageDialog(rootPane, "updated");



                } catch (Exception e) {
                        System.out.println("table data error");
                }

            }
    private void btnInventoryToHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventoryToHomeActionPerformed
        new Home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnInventoryToHomeActionPerformed

    private void btnRemoveProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveProductActionPerformed

        
        DefaultTableModel Df = (DefaultTableModel)jTable1.getModel();
        int Selected_index=jTable1.getSelectedRow();
        
        try {
                int id= Integer.parseUnsignedInt(Df.getValueAt((Selected_index),0).toString());

                
                Class.forName("com.mysql.jdbc.Driver");
                con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/shop_manage","root","Majumder@reshad");
                insert = con1.prepareStatement("delete from customer where id=? ");
                
                insert.setInt(1, id);

                
                insert.executeUpdate();
                
                JOptionPane.showMessageDialog(rootPane, "Product Deleted!");
                table_update();
                
            } catch (Exception e) {
                  System.out.println("product delete from database error");
            }

    }//GEN-LAST:event_btnRemoveProductActionPerformed

    private void btn_c_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_c_submitActionPerformed
        String C_name=txtC_name.getText();
        String C_shopName=txtC_shopName.getText();
        String C_addrress=txtC_address.getText();
        String C_mobile=txtC_mobile.getText();
        
        if (C_name.equals("") || C_shopName.equals("")||C_addrress.equals("")||C_mobile.equals("")){
            JOptionPane.showMessageDialog(rootPane, "please provide every info.");
        } else{
//            Statement s;
//            try {
//                s=DB.mycon().createStatement();
//                s.executeUpdate("INSERT INTO product (name,brand,box,description)"+ " VALUES ('"+p_name+"','"+p_brand+"','"+p_box+"','"+p_desc+"')");
//                JOptionPane.showMessageDialog(rootPane, "product added");
//            } catch (Exception e) {
//                System.out.println("database failled");
//
//            }

              try {
                Class.forName("com.mysql.jdbc.Driver");
                con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/shop_manage","root","Majumder@reshad");
                insert = con1.prepareStatement("insert into customer (name,shop_name,address,mobile)values(?,?,?,?)");
                
                insert.setString(1, C_name);
                insert.setString(2, C_shopName);
                insert.setString(3, C_addrress);
                insert.setString(4, C_mobile);
                
                insert.executeUpdate();
                
                //JOptionPane.showMessageDialog(rootPane, "updated");
                
                table_update();
                
            } catch (Exception e) {
                  System.out.println("product add to database error");
            }



            txtC_name.setText("");
            txtC_shopName.setText("");
            txtC_address.setText("");
            txtC_mobile.setText("");
        }
        
        
        
        table_update();
        
    }//GEN-LAST:event_btn_c_submitActionPerformed

    private void btnRemoveProduct1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveProduct1ActionPerformed
               //edit product info
        DefaultTableModel Df = (DefaultTableModel)jTable1.getModel();
        int Selected_index=jTable1.getSelectedRow();
        
        try {
                int id= Integer.parseUnsignedInt(Df.getValueAt((Selected_index),0).toString());
                String name=txtC_name.getText();
                String brand=txtC_shopName.getText();
                String box=txtC_address.getText();
                String desc=txtC_mobile.getText();
                
                Class.forName("com.mysql.jdbc.Driver");
                con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/shop_manage","root","Majumder@reshad");
                insert = con1.prepareStatement("update customer set name=?,shop_name=?,address=?,mobile=? where id=? ");
                
                 
                insert.setString(1, name);
                insert.setString(2, brand);
                insert.setString(3, box);
                insert.setString(4, desc);
                insert.setInt(5, id);

                
                insert.executeUpdate();
                
                JOptionPane.showMessageDialog(rootPane, "updated");
                table_update();
                
            } catch (Exception e) {
                  System.out.println("product update to database error");
            }
        
        
    }//GEN-LAST:event_btnRemoveProduct1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
                
        DefaultTableModel Df = (DefaultTableModel)jTable1.getModel();
        
        int Selected_index=jTable1.getSelectedRow();
        txtC_name.setText(Df.getValueAt(Selected_index, 1).toString());
        txtC_shopName.setText(Df.getValueAt(Selected_index, 2).toString());
        txtC_address.setText(Df.getValueAt(Selected_index, 3).toString());
        txtC_mobile.setText(Df.getValueAt(Selected_index, 4).toString());
        

    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInventoryToHome;
    private javax.swing.JButton btnRemoveProduct;
    private javax.swing.JButton btnRemoveProduct1;
    private javax.swing.JButton btn_c_submit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtC_address;
    private javax.swing.JTextField txtC_mobile;
    private javax.swing.JTextField txtC_name;
    private javax.swing.JTextField txtC_shopName;
    // End of variables declaration//GEN-END:variables
}
